import type { LucideIcon } from "lucide-react";
import {
  Building2,
  Stethoscope,
  UtensilsCrossed,
  Truck,
  ShoppingBag,
  Factory,
  Briefcase,
  Hammer,
  HardHat,
  Wrench,
  Smile,
  HandCoins,
  Hotel,
  Boxes,
  Banknote,
  Scale,
  Calculator,
  CreditCard,
  Receipt,
  LineChart,
  Plane,
  Shield,
  Flame,
  Package,
  Cog,
} from "lucide-react";

export type Service = {
  slug: string;
  title: string;
  icon: LucideIcon;
  tagline: string;
  description: string;
  bullets: string[];
  highlight: string;
};

export type Industry = {
  slug: string;
  label: string;
  icon: LucideIcon;
  hero: string;
  intro: string;
  services: Service[];
};

const make = (
  slug: string,
  title: string,
  icon: LucideIcon,
  tagline: string,
  description: string,
  bullets: string[],
  highlight: string,
): Service => ({ slug, title, icon, tagline, description, bullets, highlight });

export const INDUSTRIES: Industry[] = [
  {
    slug: "construction",
    label: "Construction",
    icon: Building2,
    hero: "Capital that breaks ground.",
    intro:
      "From ground-up commercial builds to heavy equipment, we structure financing that keeps Columbus crews moving and Franklin County projects on schedule.",
    services: [
      make(
        "construction-business-loans",
        "Construction Business Loans",
        Hammer,
        "Ground-up & renovation projects",
        "Multi-draw financing aligned to your construction schedule with interest-only periods during the build phase.",
        ["Up to 80% LTC", "12-36 month terms", "Convert to permanent financing"],
        "Funding $250K-$25M",
      ),
      make(
        "equipment-financing",
        "Construction Equipment Financing",
        HardHat,
        "Excavators, cranes, loaders",
        "Finance new or used heavy equipment with the equipment itself serving as collateral, preserving working capital for jobs.",
        ["100% financing available", "Section 179 eligible", "Approvals in 24-48 hours"],
        "Rates from 6.75%",
      ),
      make(
        "accounts-receivable-financing",
        "AR Financing for GCs",
        Receipt,
        "Borrow against AIA progress billings",
        "A revolving facility secured by your receivables — built for general contractors bridging slow-pay owners and AIA G702/G703 cycles.",
        ["Up to 90% AR advance", "Lines $250K-$20M", "Reporting-friendly"],
        "Revolving",
      ),
      make(
        "working-capital-loans",
        "Working Capital Loans",
        Banknote,
        "Bridge change orders and retainage",
        "Cover material spikes, fund change orders or bridge retainage holdbacks without giving up equity.",
        ["Lines up to $5M", "Same-day draws", "Revolving structures"],
        "Funded same week",
      ),
    ],
  },
  {
    slug: "healthcare",
    label: "Healthcare",
    icon: Stethoscope,
    hero: "Funding for those who care.",
    intro:
      "Specialized lending for medical, dental and specialty practices across Dublin, Worthington, Bexley and the broader OhioHealth and Nationwide Children's referral network.",
    services: [
      make(
        "medical-practice-loans",
        "Medical Practice Loans",
        Stethoscope,
        "Clinics & physician groups",
        "Acquisition, partner buy-in, expansion and working capital tailored to the rhythms of insurance reimbursements.",
        ["Up to 100% project financing", "Terms up to 10 years", "Deferred payment options"],
        "$50K-$7M",
      ),
      make(
        "dental-practice-loans",
        "Dental Practice Loans",
        Smile,
        "Equipment, expansion & acquisition",
        "Finance chairs, CBCT imaging, build-outs or a full practice purchase with structures designed for DSOs and solo Columbus dentists.",
        ["Chairs, imaging & software", "Practice acquisition", "Refinance existing debt"],
        "Rates from 7.25%",
      ),
      make(
        "sba-7a-loan",
        "SBA 7(a) for Practices",
        HandCoins,
        "Long-term, low-rate practice capital",
        "The SBA's flagship program — common for partner buy-ins, satellite office expansion and full practice acquisitions.",
        ["Up to $5M", "10-year working capital terms", "Real estate up to 25 years"],
        "From 8.25% APR",
      ),
      make(
        "unsecured-business-loans",
        "Unsecured Practice Loans",
        Scale,
        "No collateral, fast turnaround",
        "Cash-flow-based underwriting for established practices with strong revenue. No UCC blanket liens or hard collateral.",
        ["Funded in 1-3 days", "Terms 1-5 years", "Up to $500K"],
        "Soft pull pre-qual",
      ),
    ],
  },
  {
    slug: "hospitality",
    label: "Hospitality & Restaurants",
    icon: UtensilsCrossed,
    hero: "Fuel the next service.",
    intro:
      "Working capital, equipment financing and hotel CapEx for the operators driving the Short North, German Village, Easton and the I-270 hotel corridor.",
    services: [
      make(
        "restaurant-loans",
        "Restaurant Loans",
        UtensilsCrossed,
        "Fit-out, expansion & equipment",
        "Open a second location, refresh the dining room or weather a slow season with capital structured for Columbus hospitality cash flow.",
        ["Daily, weekly or monthly payments", "Same-day approvals", "No equity required"],
        "$25K-$2M",
      ),
      make(
        "hotel-loans",
        "Hotel Loans",
        Hotel,
        "Acquisition & PIP renovation",
        "Capital for flagged and independent properties along the I-270 corridor and Downtown Columbus: acquisitions, brand-mandated PIPs and refinances.",
        ["SBA 7(a) & 504", "Bridge to perm", "Up to 90% LTV"],
        "$500K-$25M",
      ),
      make(
        "merchant-cash-advance",
        "Merchant Cash Advance",
        CreditCard,
        "Same-day capital from card sales",
        "Fast capital advanced against future card and platform settlements — repaid as a small percentage of daily revenue.",
        ["24-hour funding", "No fixed payments", "Bad credit considered"],
        "$10K-$1M",
      ),
      make(
        "working-capital-loans",
        "Hospitality Working Capital",
        Banknote,
        "Bridge slow shoulder seasons",
        "Cover payroll, refresh inventory or fund a marketing push without giving up equity.",
        ["Daily, weekly or monthly remits", "Funded in 24 hrs", "No collateral options"],
        "$10K-$2M",
      ),
    ],
  },
  {
    slug: "transportation",
    label: "Transportation & Trucking",
    icon: Truck,
    hero: "Keep the fleet rolling.",
    intro:
      "From owner-operators on I-70 to mid-size fleets running the Midwest distribution lanes: trucks, trailers, repair bays and the working capital that holds it all together.",
    services: [
      make(
        "trucking-business-loans",
        "Trucking Business Loans",
        Truck,
        "Owner-operators to fleet expansion",
        "Capital to add tractors, cover insurance down payments, fuel up and bridge slow-pay receivables, built for Central Ohio trucking economics.",
        ["DOT-friendly underwriting", "Factoring + term combos", "Fuel & maintenance reserves"],
        "Funded in 24 hours",
      ),
      make(
        "invoice-factoring",
        "Trucking Invoice Factoring",
        Receipt,
        "Same-day cash on freight invoices",
        "Sell freight bills the day you deliver — non-recourse and recourse options with transparent advance rates.",
        ["Advance rates up to 95%", "Non-recourse available", "No long-term lock-in"],
        "24-hour funding",
      ),
      make(
        "equipment-financing",
        "Truck & Trailer Financing",
        Wrench,
        "New & used Class 8 and trailers",
        "Single units or full fleets with structures sized for owner-operators and growing carriers alike.",
        ["100% financing available", "Section 179 eligible", "Approvals in 24-48 hours"],
        "Rates from 6.99%",
      ),
      make(
        "working-capital-loans",
        "Fleet Working Capital",
        LineChart,
        "Bridge fuel, insurance and slow pay",
        "Lines of credit and short-term capital to scale operations through fuel-price swings and slow-pay shippers.",
        ["Same-day draws", "Lines up to $2M", "Revolving structures"],
        "No collateral required",
      ),
    ],
  },
  {
    slug: "retail",
    label: "Retail",
    icon: ShoppingBag,
    hero: "Stock more. Sell more.",
    intro:
      "Inventory financing, build-outs and working capital for storefronts across Easton, the Short North, Polaris and the Grandview Heights corridor.",
    services: [
      make(
        "retail-business-loans",
        "Retail Business Loans",
        ShoppingBag,
        "Inventory & storefront capital",
        "Stock up for the season, open a second location, or refresh your Columbus storefront with capital sized to retail cash flow cycles.",
        ["Seasonal payment structures", "Inventory financing", "POS-integrated underwriting"],
        "$15K-$1M",
      ),
      make(
        "business-line-of-credit",
        "Inventory Line of Credit",
        CreditCard,
        "Draw what you need, when you need it",
        "Revolving capital sized to your inventory turn — only pay interest on what you draw.",
        ["Lines $25K-$500K", "Same-day draws", "Pay interest only on used balance"],
        "Rates from 9.75%",
      ),
      make(
        "merchant-cash-advance",
        "Retail Cash Advance",
        Package,
        "Fast capital against future sales",
        "An advance against future card and platform revenue, funded fast and repaid as a small percentage of daily sales.",
        ["24-hour funding", "No fixed payments", "Bad credit considered"],
        "$10K-$1M",
      ),
      make(
        "small-business-loans",
        "Compare Retail Loan Options",
        HandCoins,
        "One application, every product",
        "Compare term loans, lines of credit, equipment and merchant cash advance through one soft-pull application.",
        ["$5K-$5M", "75+ lender network", "Soft credit pull only"],
        "Funded in 24-72 hrs",
      ),
    ],
  },
  {
    slug: "manufacturing",
    label: "Manufacturing",
    icon: Factory,
    hero: "Capital that scales the line.",
    intro:
      "Heavy equipment, working capital and receivables financing for Central Ohio manufacturers, Honda-corridor suppliers and Westside legacy producers.",
    services: [
      make(
        "manufacturing-equipment-financing",
        "Manufacturing Equipment Financing",
        Cog,
        "CNC, robotics & production lines",
        "Finance individual machines or entire production cells with structures that align to ROI timelines, including soft costs.",
        ["New & used equipment", "Soft costs included", "Step payment options"],
        "Up to $10M",
      ),
      make(
        "working-capital-loans",
        "Working Capital Loans",
        Banknote,
        "Bridge purchase orders & payroll",
        "Cover raw material spikes, fund large purchase orders or bridge customer payment terms without giving up equity.",
        ["Lines up to $5M", "Same-day draws", "Revolving structures"],
        "Funded same week",
      ),
      make(
        "invoice-factoring",
        "Invoice Factoring",
        Receipt,
        "Turn AR into cash today",
        "Sell your invoices for immediate liquidity: non-recourse and recourse options with transparent fee structures.",
        ["Advance rates up to 95%", "Non-recourse available", "No long-term contracts"],
        "24-hour funding",
      ),
      make(
        "accounts-receivable-financing",
        "Accounts Receivable Financing",
        Boxes,
        "Lines secured by your AR",
        "A revolving facility that grows with your receivables, cheaper than factoring when volume is consistent.",
        ["Up to 90% AR advance", "Maintain customer relationships", "Reporting-friendly"],
        "Lines $250K-$20M",
      ),
    ],
  },
  {
    slug: "professional-services",
    label: "Professional Services",
    icon: Briefcase,
    hero: "Capital for the firm.",
    intro:
      "Tailored financing for Columbus law firms, accounting practices, consulting groups and other partner-led firms — Downtown, Bexley, Dublin and Worthington.",
    services: [
      make(
        "unsecured-business-loans",
        "Unsecured Partner Capital",
        Briefcase,
        "Partner buy-ins & lateral hires",
        "Partner buy-ins, lateral hires, technology and office build-outs financed around partner draw cycles.",
        ["Unsecured options to $500K", "Partner buy-in financing", "Tech & build-out included"],
        "Soft pull pre-qual",
      ),
      make(
        "business-line-of-credit",
        "Business Line of Credit",
        CreditCard,
        "Draw what you need, when you need it",
        "Revolving capital that's there when AR slows or a new matter ramps up. Only pay interest on what you draw.",
        ["Lines $25K-$500K", "Same-day draws", "Pay interest only on used balance"],
        "Rates from 9.75%",
      ),
      make(
        "revenue-based-financing",
        "Revenue Based Financing",
        LineChart,
        "Pay as you collect",
        "Capital priced as a fixed multiple, repaid as a percentage of monthly revenue. No equity, no fixed installments.",
        ["No equity dilution", "Flexible repayment", "$50K-$5M"],
        "Pay as you earn",
      ),
      make(
        "small-business-loans-near-me",
        "Local Loan Advisors",
        Calculator,
        "Columbus-based loan brokering",
        "Access 75+ vetted lenders through one application. We negotiate term sheets and present the best two or three.",
        ["75+ lender network", "One application", "We negotiate on your behalf"],
        "No fee until close",
      ),
    ],
  },
  {
    slug: "oilfield-services",
    label: "Industrial & Manufacturing",
    icon: Flame,
    hero: "Capital that drives production.",
    intro:
      "Equipment, working capital and AR factoring for Central Ohio industrial operators, specialty manufacturers and Midwest supply-chain businesses.",
    services: [
      make(
        "oilfield-services-loans",
        "Manufacturing & Industrial Loans",
        Flame,
        "Production lines & industrial equipment",
        "Equipment, working capital and AR factoring for manufacturers and industrial service operators in the Columbus metro.",
        ["AR factoring for slow-pay contracts", "Equipment & rolling stock", "Bridge through slow quarters"],
        "Up to $5M",
      ),
      make(
        "invoice-factoring",
        "Industrial Invoice Factoring",
        Receipt,
        "Same-day cash on production invoices",
        "Sell invoices to slow-pay OEM customers the day you ship — purpose-built for 60-90 day manufacturing payment cycles.",
        ["Advance rates up to 95%", "Non-recourse available", "Funded in 24 hours"],
        "Same-day cash",
      ),
      make(
        "equipment-financing",
        "Industrial Equipment Financing",
        Wrench,
        "CNC, presses and production lines",
        "Finance new and used industrial equipment with the equipment itself as collateral.",
        ["100% financing available", "Section 179 eligible", "Approvals in 24-48 hours"],
        "Rates from 6.99%",
      ),
      make(
        "accounts-receivable-financing",
        "Asset-Based Lending",
        Boxes,
        "Revolving line on the AR ledger",
        "A revolving facility secured by your receivables — cheaper than factoring at consistent volume.",
        ["Up to 90% AR advance", "Reporting-friendly", "Lines $250K-$20M"],
        "Revolving",
      ),
    ],
  },
  {
    slug: "defense-aerospace",
    label: "Defense & Tech Corridor",
    icon: Plane,
    hero: "Capital for Rickenbacker-adjacent operators.",
    intro:
      "Columbus is home to Rickenbacker Air National Guard Base and a deep base of defense-adjacent logistics, tech and government-contract operators. Whitfield finances cleared and veteran-owned operators with SBA Express, equipment and government-contract working capital.",
    services: [
      make(
        "veteran-business-loans",
        "SBA Express for Veterans",
        Shield,
        "Fast-track funding for veteran owners",
        "Expedited SBA Express loans for veteran-owned businesses with reduced fees and 36-hour SBA turnaround.",
        ["Up to $500K", "Reduced SBA fees for veterans", "36-hour SBA turnaround"],
        "Veteran-friendly",
      ),
      make(
        "accounts-receivable-financing",
        "Govt Contract AR Financing",
        Receipt,
        "Borrow against federal receivables",
        "A revolving line secured by federal and prime-contractor receivables. Lender comfort with FAR-billed AR.",
        ["Up to 90% AR advance", "FAR-billing friendly", "Lines $250K-$20M"],
        "Revolving",
      ),
      make(
        "working-capital-loans",
        "Contract Mobilization Capital",
        Banknote,
        "Stand up the contract before the first invoice clears",
        "Working capital to mobilize crews, buy materials and staff up before the first government payment hits.",
        ["$10K-$2M", "Daily, weekly or monthly payments", "No collateral options"],
        "Funded in 24 hrs",
      ),
      make(
        "sba-7a-loan",
        "SBA 7(a) for Defense Contractors",
        HandCoins,
        "Long-term capital for cleared firms",
        "Use SBA 7(a) for acquisition, expansion or real estate — popular among Rickenbacker-area tenants and defense IT firms.",
        ["Up to $5M", "10-year working capital terms", "Real estate up to 25 years"],
        "From 8.25% APR",
      ),
    ],
  },
  {
    slug: "distribution",
    label: "Distribution & Logistics",
    icon: Package,
    hero: "Capital that ships on time.",
    intro:
      "Working capital, equipment and AR financing for the warehouses and 3PLs along the I-270 ring, I-70/I-71 corridor and the Columbus distribution hubs.",
    services: [
      make(
        "accounts-receivable-financing",
        "3PL Accounts Receivable Financing",
        Boxes,
        "Revolving line on shipper AR",
        "A revolving facility secured by your receivables, sized for 3PLs and freight brokers with consistent invoice volume.",
        ["Up to 90% AR advance", "Lines $250K-$20M", "Reporting-friendly"],
        "Revolving",
      ),
      make(
        "invoice-factoring",
        "Freight Bill Factoring",
        Receipt,
        "Same-day cash on shipper invoices",
        "Sell freight invoices the day you deliver — non-recourse and recourse options.",
        ["Advance rates up to 95%", "Non-recourse available", "24-hour funding"],
        "Same-day cash",
      ),
      make(
        "revenue-based-financing",
        "Revenue-Based Financing",
        LineChart,
        "Pay as you ship",
        "Non-dilutive growth capital priced as a fixed multiple, repaid as a percentage of monthly revenue.",
        ["$50K-$5M", "No equity dilution", "Flexible repayment"],
        "Pay as you earn",
      ),
      make(
        "equipment-financing",
        "Warehouse Equipment Financing",
        Wrench,
        "Racking, forklifts and conveyors",
        "Finance racking systems, forklifts and conveyor lines with the equipment itself as collateral.",
        ["100% financing available", "Section 179 eligible", "Approvals in 24-48 hours"],
        "Rates from 6.99%",
      ),
    ],
  },
];

export function getIndustry(slug: string): Industry | undefined {
  return INDUSTRIES.find((i) => i.slug === slug);
}
