// Long-form body copy per Columbus neighborhood - used by
// columbus.$suburb.tsx to lift pages above the 700-word threshold.

export const SUBURB_BODIES: Record<string, string[]> = {
  "downtown-columbus": [
    "Downtown Columbus is the state capital and the region's professional-services core — the Ohio Statehouse, the Columbus Commons, the Scioto Mile riverfront, COSI and a deep base of law firms, lobbying shops and accounting practices clustered around High Street and Broad Street. Cash flow here runs on the legislative calendar, the conference trade and the lunchtime rush from government offices. Rent and build-out costs along Broad Street and the Scioto Mile run materially above the metro average, which means working capital structure and bridge financing matter more here than in the suburbs.",
    "Whitfield Credit has routed Downtown Columbus deals across three recurring patterns: professional-services partner buy-ins (often unsecured, structured around partner draw cycles), restaurant working capital lines that smooth session-driven and conference-driven cash flow, and SBA 7(a) acquisition deals when established Downtown operators transition ownership. SBA 504 fits when a Downtown firm finally stops renting and buys the Broad Street frontage it has occupied for years. For event-driven food-and-beverage operators, working capital lines cover the gap between fixed lease costs and uneven monthly revenue tied to Statehouse activity and convention bookings.",
  ],
  "short-north": [
    "The Short North runs along High Street between Downtown and OSU — a dense corridor of galleries, chef-driven restaurants, boutique retail and creative studios that hosts the monthly Gallery Hop, the Goodale Park weekend trade and a steady flow of OSU event and conference traffic. Foot traffic here is heavy and weekend-skewed, producing a revenue pattern more like a destination district than a neighborhood retail strip. Rent per square foot along the Gallery Hop corridor rivals German Village as the highest in the metro outside Downtown.",
    "Whitfield Credit routes Short North financing around build-outs, equipment + working capital combos and SBA 7(a) acquisitions when long-running concepts transition owners. Gallery Hop-driven retailers and studio operators benefit most from revenue-based financing — payments flex with the event-driven sales cycle rather than forcing a fixed monthly installment. For chef-driven concepts scaling from one to two locations, SBA 7(a) handles the acquisition cleanly at 10% down with the goodwill financing included. Pre-screen always starts with use of funds, because the right lender bench for a Short North restaurant expansion differs from the right bench for a boutique retail acquisition.",
  ],
  "german-village": [
    "German Village is Columbus's historic brick-street district south of Downtown — Schiller Park, the Book Loft, Schmidt's Sausage Haus, classic European restaurants and a tight cluster of boutiques, professional offices and bed-and-breakfasts. The district's preservation overlay keeps rents high and build-out costs higher — every renovation has to meet the German Village Commission's standards. Operators here tend to be long-tenured and brand-loyal, with strong underwriting profiles built on years of consistent foot traffic.",
    "Whitfield Credit finances German Village owners through SBA 7(a) for boutique and restaurant acquisitions, working capital lines and SBA 504 owner-occupied purchases when an operator buys the brick frontage they've leased for a decade. Succession deals are common here — several Schiller Park-area restaurants and shops are now in second- or third-generation transitions, a high-fit use case for SBA 7(a) with earn-out structures when incoming buyers need to bridge the purchase price gap. Equipment financing handles the periodic kitchen refresh and CBCT upgrades for the dental practices on the district's periphery.",
  ],
  "dublin": [
    "Dublin sits along I-270 northwest of Columbus — the Bridge Park mixed-use development, the corporate campuses of Cardinal Health and Wendy's HQ, the Memorial Tournament at Muirfield Village and a thick base of tech-enabled professional services. Operators here are typically white-collar, scale-oriented and well-credentialed, which produces clean underwriting profiles and a high fit for unsecured working capital and revenue-based products. The Bridge Park riverfront development has added a new wave of chef-driven restaurants and boutique retail alongside the legacy corporate-corridor operators.",
    "Whitfield Credit routes Dublin financing toward growth capital — hiring ramps, marketing spend and partner buy-ins — rather than the equipment-heavy mix more common in Hilltop or South Columbus. Revenue-based financing fits Bridge Park SaaS and professional service firms that need growth capital without giving up equity. SBA 7(a) handles partner buy-ins and acquisitions for the Muirfield corridor's medical and dental practices, where predictable insurance reimbursement cycles produce clean underwriting. Unsecured working capital lines up to $500K cover the in-between work for established Dublin firms that don't want to take on a blanket UCC.",
  ],
  "westerville": [
    "Westerville sits at the northeast edge of Franklin County along I-71 — Otterbein University, Uptown Westerville's historic Main Street, Polaris-area retail and a deep base of family-owned trades and professional offices. Operators here trend long-tenured and second-generation, with strong underwriting profiles built on consistent revenue and a high share of succession deals. The Polaris corridor adds a layer of franchise and corporate-adjacent operators alongside the Uptown Main Street boutiques.",
    "Whitfield Credit routes Westerville financing across SBA 7(a) family-business successions, equipment financing for trades and SBA 504 owner-occupied real estate purchases. HVAC, plumbing and electrical operators along the I-71 corridor finance trucks and equipment with the rolling stock as collateral. For Uptown Westerville boutique retailers and restaurants, revolving lines handle the seasonal inventory cycle and the event-driven sales swings around Otterbein's calendar. Succession deals — children or outside buyers stepping into established Westerville family businesses — are among the most common Whitfield Credit closes in the northeast suburbs.",
  ],
  "bexley": [
    "Bexley — an independent municipality inside Columbus's footprint along Main Street and Drexel Avenue — concentrates a deep base of independent retail, dental practices and professional services, plus Capital University and the Jeffrey Mansion. Operators here trend more established than the metro average, with strong underwriting profiles and a high share of second- and third-generation succession deals along Main Street. The independent-municipality structure means Bexley operators face a separate permitting and zoning process from the City of Columbus — something that can slow build-out timelines and affect draw schedules on construction-tied financing.",
    "Whitfield Credit routes Bexley financing through SBA 7(a) acquisitions, SBA 504 real estate purchases and unsecured working capital lines for the in-between work. Dental practice acquisitions along Main Street are a recurring pattern — the neighborhood's affluent and stable patient base produces underwriting profiles that clear SBA 7(a) at its most competitive pricing tier. For boutique retail and professional-services firms buying the Drexel Avenue storefront they've leased, SBA 504 covers the commercial real estate at 10% down with the building as collateral.",
  ],
  "hilltop": [
    "The Hilltop sits west of Downtown along Broad Street and Sullivant Avenue — a deep base of family-owned light manufacturers, auto shops, panaderías and trades that have anchored this community for generations. Operators here trend long-tenured and family-owned, with strong cash-flow histories but often underbanked relative to their north-side peers. Equipment ages faster here than the underwriting on it, which is why equipment financing and SBA 504 real estate structures dominate the Hilltop financing mix.",
    "Whitfield Credit routes Hilltop financing across two recurring patterns: equipment loans and SBA 504 real estate purchases for legacy operators ready to modernize, and SBA 7(a) acquisitions for second-generation buyers taking over family businesses. Equipment loans cover CNC machines, frame racks, paint booths and baking production lines with the gear as collateral — preserving the operating cash flow for payroll and materials. For operators who've rented the same Sullivant Avenue storefront for twenty years, SBA 504 at 10% down finally gives them the path to ownership. The pre-screen always starts with the collateral picture, because the right lender bench for a Hilltop metal fabricator isn't the right bench for a Hilltop restaurant.",
  ],
  "worthington": [
    "Worthington sits north of Columbus along High Street and SR-161 — the Historic District around the Worthington Inn, the Linworth corridor's restaurants and a thick base of professional offices, medical practices and corporate-adjacent service firms along the I-270 frontage. Operators trend established and professionally licensed, with clean underwriting profiles that fit SBA 7(a) and unsecured working capital products cleanly. The historic district overlay makes renovation and build-out more complex, which elevates the importance of construction-draw structures for restoration-heavy projects.",
    "Whitfield Credit routes Worthington deals through unsecured working capital lines, SBA 7(a) for medical and dental practice acquisitions, and SBA 504 for owner-occupied medical-office purchases. Old Worthington-area medical and dental practices are among the cleanest SBA 7(a) underwriting profiles in the metro — stable revenue, predictable insurance cycles and an affluent patient base. Financial services firms and CPA practices along High Street use unsecured working capital lines up to $500K for hiring ramps and marketing spend without the UCC blanket lien that would complicate their balance sheet.",
  ],
  "easton": [
    "Easton is a planned mixed-use district in the northeast quadrant of Columbus — anchored by Easton Town Center, a deep base of restaurants and specialty retail, plus the office campuses along Easton Way. Operators here face high rent, high build-out costs and a customer base that expects a polished experience. The Easton tenant mix trends franchise and corporate, but there's a growing layer of independent concept-driven operators — the segment Whitfield Credit serves most actively.",
    "Whitfield Credit routes Easton financing around customer concentration, seasonality and the rent base. Revolving lines cover the inventory cycle for specialty retailers whose fourth-quarter revenue is 40% of the annual total. SBA 7(a) handles new-concept build-outs for independent operators negotiating first-time Easton leases — the build-out package, initial inventory and pre-opening working capital can all be wrapped into a single SBA 7(a) close. Revenue-based financing fits fast-growing Easton boutique brands that need growth capital without a fixed monthly installment tied to a lease-heavy cost structure.",
  ],
  "grandview-heights": [
    "Grandview Heights — an independent municipality between Downtown and Upper Arlington along Grandview Avenue and 5th Avenue — concentrates a tight base of independent boutique retail, professional offices, chef-driven restaurants and creative studios. Operators here are smaller, more design-forward and more event-tied than in Dublin or Worthington, which produces choppier monthly revenue and a higher reliance on flexible working capital. The independent-municipality overlay adds a separate permitting process that can affect construction draw timelines.",
    "Whitfield Credit finances Grandview operators with SBA 7(a) acquisitions, equipment + working capital combos for restaurants and revenue-based financing for design and creative firms. Revenue-based financing is particularly well-suited to Grandview Heights boutique brands and creative studios — payments flex with the event-driven and weekend-skewed revenue cycle rather than forcing a fixed monthly installment. For chef-driven restaurants along Grandview Avenue adding equipment or scaling into a second service, a combined equipment loan and working capital structure covers both the gear and the operating ramp simultaneously.",
  ],
};
