/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VirginiaBeachRouteImport } from './routes/virginia-beach'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApplyNowRouteImport } from './routes/apply-now'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VirginiaBeachSuburbRouteImport } from './routes/virginia-beach.$suburb'
import { Route as PillarSlugRouteImport } from './routes/pillar.$slug'
import { Route as IndustrySlugRouteImport } from './routes/industry.$slug'
import { Route as VirginiaBeachSuburbPillarRouteImport } from './routes/virginia-beach.$suburb.$pillar'

const VirginiaBeachRoute = VirginiaBeachRouteImport.update({
  id: '/virginia-beach',
  path: '/virginia-beach',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyNowRoute = ApplyNowRouteImport.update({
  id: '/apply-now',
  path: '/apply-now',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VirginiaBeachSuburbRoute = VirginiaBeachSuburbRouteImport.update({
  id: '/$suburb',
  path: '/$suburb',
  getParentRoute: () => VirginiaBeachRoute,
} as any)
const PillarSlugRoute = PillarSlugRouteImport.update({
  id: '/pillar/$slug',
  path: '/pillar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustrySlugRoute = IndustrySlugRouteImport.update({
  id: '/industry/$slug',
  path: '/industry/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VirginiaBeachSuburbPillarRoute =
  VirginiaBeachSuburbPillarRouteImport.update({
    id: '/$pillar',
    path: '/$pillar',
    getParentRoute: () => VirginiaBeachSuburbRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply-now': typeof ApplyNowRoute
  '/contact': typeof ContactRoute
  '/virginia-beach': typeof VirginiaBeachRouteWithChildren
  '/industry/$slug': typeof IndustrySlugRoute
  '/pillar/$slug': typeof PillarSlugRoute
  '/virginia-beach/$suburb': typeof VirginiaBeachSuburbRouteWithChildren
  '/virginia-beach/$suburb/$pillar': typeof VirginiaBeachSuburbPillarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply-now': typeof ApplyNowRoute
  '/contact': typeof ContactRoute
  '/virginia-beach': typeof VirginiaBeachRouteWithChildren
  '/industry/$slug': typeof IndustrySlugRoute
  '/pillar/$slug': typeof PillarSlugRoute
  '/virginia-beach/$suburb': typeof VirginiaBeachSuburbRouteWithChildren
  '/virginia-beach/$suburb/$pillar': typeof VirginiaBeachSuburbPillarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply-now': typeof ApplyNowRoute
  '/contact': typeof ContactRoute
  '/virginia-beach': typeof VirginiaBeachRouteWithChildren
  '/industry/$slug': typeof IndustrySlugRoute
  '/pillar/$slug': typeof PillarSlugRoute
  '/virginia-beach/$suburb': typeof VirginiaBeachSuburbRouteWithChildren
  '/virginia-beach/$suburb/$pillar': typeof VirginiaBeachSuburbPillarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply-now'
    | '/contact'
    | '/virginia-beach'
    | '/industry/$slug'
    | '/pillar/$slug'
    | '/virginia-beach/$suburb'
    | '/virginia-beach/$suburb/$pillar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply-now'
    | '/contact'
    | '/virginia-beach'
    | '/industry/$slug'
    | '/pillar/$slug'
    | '/virginia-beach/$suburb'
    | '/virginia-beach/$suburb/$pillar'
  id:
    | '__root__'
    | '/'
    | '/apply-now'
    | '/contact'
    | '/virginia-beach'
    | '/industry/$slug'
    | '/pillar/$slug'
    | '/virginia-beach/$suburb'
    | '/virginia-beach/$suburb/$pillar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyNowRoute: typeof ApplyNowRoute
  ContactRoute: typeof ContactRoute
  VirginiaBeachRoute: typeof VirginiaBeachRouteWithChildren
  IndustrySlugRoute: typeof IndustrySlugRoute
  PillarSlugRoute: typeof PillarSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/virginia-beach': {
      id: '/virginia-beach'
      path: '/virginia-beach'
      fullPath: '/virginia-beach'
      preLoaderRoute: typeof VirginiaBeachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-now': {
      id: '/apply-now'
      path: '/apply-now'
      fullPath: '/apply-now'
      preLoaderRoute: typeof ApplyNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virginia-beach/$suburb': {
      id: '/virginia-beach/$suburb'
      path: '/$suburb'
      fullPath: '/virginia-beach/$suburb'
      preLoaderRoute: typeof VirginiaBeachSuburbRouteImport
      parentRoute: typeof VirginiaBeachRoute
    }
    '/pillar/$slug': {
      id: '/pillar/$slug'
      path: '/pillar/$slug'
      fullPath: '/pillar/$slug'
      preLoaderRoute: typeof PillarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/$slug': {
      id: '/industry/$slug'
      path: '/industry/$slug'
      fullPath: '/industry/$slug'
      preLoaderRoute: typeof IndustrySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virginia-beach/$suburb/$pillar': {
      id: '/virginia-beach/$suburb/$pillar'
      path: '/$pillar'
      fullPath: '/virginia-beach/$suburb/$pillar'
      preLoaderRoute: typeof VirginiaBeachSuburbPillarRouteImport
      parentRoute: typeof VirginiaBeachSuburbRoute
    }
  }
}

interface VirginiaBeachSuburbRouteChildren {
  VirginiaBeachSuburbPillarRoute: typeof VirginiaBeachSuburbPillarRoute
}

const VirginiaBeachSuburbRouteChildren: VirginiaBeachSuburbRouteChildren = {
  VirginiaBeachSuburbPillarRoute: VirginiaBeachSuburbPillarRoute,
}

const VirginiaBeachSuburbRouteWithChildren =
  VirginiaBeachSuburbRoute._addFileChildren(VirginiaBeachSuburbRouteChildren)

interface VirginiaBeachRouteChildren {
  VirginiaBeachSuburbRoute: typeof VirginiaBeachSuburbRouteWithChildren
}

const VirginiaBeachRouteChildren: VirginiaBeachRouteChildren = {
  VirginiaBeachSuburbRoute: VirginiaBeachSuburbRouteWithChildren,
}

const VirginiaBeachRouteWithChildren = VirginiaBeachRoute._addFileChildren(
  VirginiaBeachRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyNowRoute: ApplyNowRoute,
  ContactRoute: ContactRoute,
  VirginiaBeachRoute: VirginiaBeachRouteWithChildren,
  IndustrySlugRoute: IndustrySlugRoute,
  PillarSlugRoute: PillarSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
